Schmavery/facebook-chat-api

index.js

When logging in with a standard account, the `api` variable was not properly passed to the callback.

Fix non-page login

---

README.md
src/getUserId.js
src/sendDirectMessage.js
src/sendDirectSticker.js

Fixed the following issue, https://github.com/Schmavery/facebook-chat-api/issues/26, by changing references to `resData.entries` to `resData.payload.entries`

Fixed resData.entries error

---

index.js
src/sendTypingIndicator.js
src/typing.js

Send typing indicator for other users in the chat to see.
The typing indicator will disappear automatically after 30 seconds or after sending a message (```api.sendMessage```).
However, this can be overridden by sending a request again, with the field ```typ``` being ```0``` instead of ```1```.
Still thinking the best idea to implement this tho.
Any suggestion?

Add api.sendTypingIndicator

---

index.js
src/sendMessage.js
src/uploadAttachment.js
utils.js

This should solve #43 
It's a little different than @Schmavery has had envisioned. Instead of using different function to allow attachment upload, i'll be using ```api.sendMessage``` by passing an object containing the **body** (string) and **attachment** (readable stream or an array of readable stream). I think this is much simpler.
```
var msg = {
body: 'message body',
attachment: fs.createReadStream(__dirname + '/image.jpg')
}
api.sendMessage(msg, message.thread_id)
```
```api.sendMessage``` will still support passing string in the first argument, so the current example in the documentation still works.
As for the ```api.uploadAttachment```,
it's a function to *upload* the attachment, it will return the attachment id to be passed in the message form. The ```api.sendMessage``` will …

Add attachment upload

---

index.js
src/archiveThread.js
src/deleteMessage.js
src/deleteThread.js
src/listen.js
src/unarchiveThread.js
utils.js

This also adds message_id (mid) to message objects.
In my current project I required being able to run these methods (particularly deleteMessage and archiveThread).
Usage is fairly simple:
**deleteMessage**
api.deleteMessage(message.message_id, function(err) {
if(err) { 
console.log('Error while deleting message..');
} 
});
**deleteThread**
api.deleteThread(message.thread_id, function(err) {
if(err) { 
console.log('Error while deleting a thread..');
} 
});
**archiveThread**
api.archiveThread(message.thread_id, function(err) {
if(err) { 
console.log('Error while archiving a thread..');
} 
});
**unarchiveThread**
api.deleteMessage(thread_to_unarchive, function(err) {
if(err) { 
console.log('Error while unarchiving a thread..');
} 
});

Adding deleteMessage, deleteThread, archiveThread, and unarchiveThread endpoints.

---

utils.js

Timestamp used to be included pre 1.0. I'm migrating to the new version and noticed timestamp was missing.

Include timestamp in formatMessage

---

src/searchForThread.js

See the following image:
The Facebook API uses limit: 21 when it hits search_threads.php. Unless it was intentional to only search for a single thread, I think it was a typo.

Limit thread query from 1 --> 21

---

utils.js

This switch statement didn't account for "video" attachments. See this gist for a full video object returned from the Facebook API: https://gist.github.com/bbatliner/c5c702b9dc9c07c080c3. Let me know if you need/don't need any of the properties.

Add "video" to attachment list

---

utils.js

I was trying to load some old conversations and received an error saying could not access `map` of `undefined`. I think Facebook used to pass an undefined array in `attachments`, and this small change accounts for that.

Account for undefined attachments in formatAttachment

---

DOCS.md
src/sendMessage.js

Send back Facebook's message timestamp in the sendMessage endpoint.
I think this is necessary because Facebook's timestamps are different than my local machines'. For example, when I receive a message (with `listen()`), my Date.now() is 15 seconds off from the message's timestamp that I received from Facebook. This causes issues when users send/receive messages in a short amount of time. Using Facebook's timestamps everywhere should resolve the timestamp discrepancies I'm seeing.
Side note: is there a reason the whole message object isn't sent back?

Return timestamp in sendMessage

---

README.md

Changed the event.thread_id to event.threadID so that it corresponds with the rest of the documentation.

Changed to threadID

---

DOCS.md

The link in the docs currently jumps to searchForThread.

Fix internal link to api.getThreadHistory

---

utils.js

``reader`` and ``threadID`` in all events is always string, except for read_receipt.
Also, i want to ask, why is the key which contain the sender id is different in every event? (senderID, author, from, reader)

Fix type inconsistency in read_receipt event

---

DOCS.md

If login function is used with {pageId: 'xxx'}, it raises a Warning:
WARN Unrecognized option given to setOptions pageId.
Changing to pageID fixes the problem

Fix: change pageId to pageID on DOCS.md

---

src/logout.js

Fixes #126 
Considering the tests were already catching this regression (see below), I saw no need to modify them. I'm still unsure as to why I receive an element with `label` of `Log out` and others receive `Log Out`. At first I considered facebook could be sending different content based on country (I'm in Canada), but that turned out not to be the case.
```
> facebook-chat-api@1.0.4 test /Users/andyjbas/code/facebook-chat-api
> mocha
Login:
1) should log out
0 passing (6s)
1 failing
1) Login: should log out:
TypeError: Cannot read property 'markup' of undefined
at src/logout.js:24:31
at Array.filter (native)
at src/logout.js:23:42
at tryCatcher (node_modules/bluebird/js/main/util.js:26:23)
at Promise._settlePromiseFromHandler (node_modules/bluebird/js/main/promise.js:507:31)
at …
```

Use more stable lookup method for logout element filter

---

src/getOnlineUsers.js

Previously all users returned from this API had to be online, as it used the nowAvailableList as the lookup. 
This change instead uses the last_active_times list as the lookup, and any person not found in the nowAvailableList is by-default 'offline'.
The offline status field was always included in the response, so I think this change shouldn't cause any problems unless people were always relying that the users were online instead of checking that field. If that's the case, then I guess this is somewhat of a breaking change...
I only want this to get the last active time - getFriendsList would be a better place for that, but I presume that the data is not included in that response.

Include offline users in getOnlineUsers (as offline)

---

src/sendMessage.js

The body doesn't get deleted when a message has a sticker.
Deleted body from `form` object rather than `msg` object.

fixed deleting body on sticker presence

---

utils.js

I think its useless to parse everytime a same revision number, when the html variable is still same too.

Make revision to parse only once

---

package.json

In node, `require('facebook-chat-api')` will try and load `server.js` (and fail), then fallback to `index.js`.
This is fine if you're using node, but I'm using [jspm](http://jspm.io/) which isn't too happy and errors with 'unable to find server.js'. Yes, this could be fixed on jspm's end, but it still leaves the unknown server.js reference in this package which might cause problems for other package managers (and even npm/node in the future?), so it'd be best to fix it here.

Remove extraneous and invalid main

---

src/addUserToGroup.js
src/changeGroupImage.js
src/sendMessage.js
src/setTitle.js

Related to bug #311. Pull request #315 only attempted to fix sendMessage, this includes 3 more services.
Functions updated:
- addUserToGroup
- changeGroupImage
- sendMessage
- setTitle
Changes made:
- Remove `message_batch[0]`
- Change https://www.facebook.com/ajax/mercury/send_messages.php to https://www.facebook.com/messaging/send/
The unit testing currently produces 30 passes and 5 failures for me.
- Login As Page:
1. should send text message object (user)
2. should send sticker message object (user)
3. should send basic string (user)
4. should get a list of online users
- Login:
5) should get a list of online users
The errors indicate:
- The URL for getOnlineUsers, https://www.facebook.com/ajax/chat/buddy_list.php, also returns a 404. I haven't been able to find the new URL and/or …

update to improve compatibility with new api

---

README.md

Sorry, the last commit did not go through completely.
I tested it with `marky-markdown`, the problem was that the `a` tag  was not closed.
I closed it and moved it after the title.
For clarification, I was talking about the html rendering of the `README.md` file on [npm](https://github.com/Schmavery/facebook-chat-api)

Fix: Avoid bad rendering of README on npm

---

src/markAsRead.js

Pull request from issue #329. All unit tests pass.
Note that I have not noticed that these changes are necessary for markAsRead to function as intended. The issue with #329 only happens on one thread that I know of, and appears to be an issue with Facebook, not this API. While investigating, I found that the official site included more parameters than this API did. These parameters may become important at some time in the future.

markAsRead has additional parameters

---

package.json

this fixes compatibility with yarn which doesn't allow you to install packages that don't allow your current node version
cheers! :smile:

allow node versions > 4

---

src/getThreadHistory.js
utils.js

getThreadHistory: Filter out messages containing error attachments

---

utils.js

The message objects have a member called 'tags'. The value of this member is an array.
Example:
`"tags": ["pages_comm_instant_reply","cg-enabled","sent","source:titan:web","inbox"]`
Example use case: For me, the "pages_comm_instant_reply" tag is important to identify, as this shows that the message is an Instant Reply:
https://www.facebook.com/help/1615627532020480
Tested on user threads and page threads.

Adding tags to formatMessage()

---

index.js
src/addUserToGroup.js
src/changeArchivedStatus.js
src/changeBlockedStatus.js
src/changeGroupImage.js
src/changeNickname.js
src/changeThreadColor.js
src/changeThreadEmoji.js
src/createPoll.js
src/deleteMessage.js
src/deleteThread.js
src/getFriendsList.js
src/getThreadHistory.js
src/getThreadInfo.js
src/getThreadList.js
src/getUserID.js
src/getUserInfo.js
src/handleMessageRequest.js
src/listen.js
src/logout.js
src/markAsRead.js
src/muteThread.js
src/removeUserFromGroup.js
src/sendMessage.js
src/sendTypingIndicator.js
src/setTitle.js
utils.js

Throughout the library there were log npmlog calls with a missing prefix (i.e. passing the message as the prefix). Fixed that.
Also removed redundant "Error in someFunction" in the prefix/message since this information is present in the function call (e.g. log.error, log.warn)

Consistent log prefixes and messages

---

DOCS.md
src/getThreadList.js

This allows users to deal with threads in the "hidden" inbox folder where Facebook sometimes auto routes incoming messages.

Make it possible to fetch threads from the 'other' folder

---

src/listen.js

Without parentheses around the calculation, string logic evaluates to NaN in the logging from listen.js:

Fix NaN in listen logs

---

DOCS.md
README.md

* Sort api functions alphabetically
* Add example how to use Github version (a.k.a _Bleeding Edge_) of facebook-chat-api instead of NPM version (_stable_)
* Change examples to use _appState_ instead of _email_+_password_ login
(it is easier to use, you only have to login once and you don't have to put your password in every source file…)
* Add
```js
const fs = require("fs");
const login = require("facebook-chat-api");
```
to examples where it was missing
* Some blocks of code were using 2 spaces as indentation - changed to 4 spaces, to match the rest
* change callbacks in examples from these inconsistent forms:
* `function callback(err, api){}`
* `function callback (err, api) {}`
* `function(err, api) {}`
* `function (err, api) {}`
(and few other)
to a single, simpler form:
* `(err, api) …

Multiple updates and fixes to DOCS and README

---

DOCS.md
README.md
index.js
src/listen.js
src/resolvePhotoUrl.js
utils.js

We can get photo attachments not only through `listen()` where the photo URL resolving was originally implemented, but also through `getThreadHistory()` where the `url` property of photos gets returned as `undefined`. I thought about resolving the URLs there but it didn't seem like a good idea, and would've probably made `getThreadHistory()` significantly slower.
So I think it's a good idea to expose this function to developers, so they can resolve photo URLs whenever they deem necessary.
I've implemented it in `utils.js` so we can reuse the code in `api.listen()` and `api.resolvePhotoUrl()`.

Expose resolvePhotoUrl() for resolving URLs on demand

---

index.js
src/addUserToGroup.js
src/changeGroupImage.js
src/getThreadList.js
src/removeUserFromGroup.js
src/sendMessage.js
src/setTitle.js
utils.js

Ran into an issue with async functions since `utils.getType(options) === 'Function'` only checks for regular Functions, and `utils.getType(options)` returns `AsyncFunction` for Async Functions.

async support

---

DOCS.md
src/listen.js
utils.js

Returning a list of people (similar to presence) with type of status and timestamp. This event trigger on first pull and in some intervals (server-side, cannot be triggered manually)
BTW. both (chatproxy_presence and buddylist_overlay) returning a field "vc" (in chatproxy_presence).
As far I investigated it have something with status "Active on Messenger"

Adding chatproxy_presence aka buddyList

---

src/getFriendsList.js
src/getUserID.js
utils.js

This uses string functions substr and indexOf to strip `fbid:` from senderID as referred in my issue. 
This should be compatible whether the senderID has the `fbid:` prefix or not. If the senderID string does not have the prefix, it will do substr(0) which will not strip anything.

Strip 'fbid:' from message senderID in util.js

---

DOCS.md
README.md
index.js
src/forwardAttachment.js

You can forward various attachments for multiple users.
Actually I tested videos and images. GIFs should work too.
Can anyone test forwading files and audio files?

Attachment forwarding

---

DOCS.md
src/listen.js

i was shocked when `api.sendMessage(event.reaction, event.threadID);` was not sending anything... :cry:

message_reaction: threadId -> threadID etc.

---

src/getThreadPictures.js

By documentation, there need to be `err` property

Adding err to getThreadPictures callback

---

DOCS.md
src/getThreadHistory.js

Since `thread_info.php` pretty much ignores the offset data, I thought it would be better to remove that option from the api as it may cause some confusion (as it did to me).
So I changed getThreadHistory to only require `amount` and `timestamp` to get the thread history. I also provided an example of how to load batches of messages in order (like scrolling up on a messenger client) without the need of `offset` functionality. However this means you cannot load messages in history without loading the messages before (more recent) it. Although you couldn't do this before anyhow.

getThreadHistory parameters adjustments

---

DOCS.md
src/sendMessage.js

Added the ability to use mentions in the sendMessage object so that a bot can ping specific people. 
Main issue is that tag location is determined with `indexOf` which is a bit scrappy. It provides a good balance of ease of use as the tag text can just be passed in, instead of the user having to figure out where the tag is in the string themselves. Can be changed to also explicitly take in beginning + ending index of the string as well.

Added Mentions

---

DOCS.md
src/sendTypingIndicator.js

I was getting this error:
```
Unhandled rejection TypeError: callback is not a function
at /var/www/node/messenger/node_modules/facebook-chat-api/src/sendTypingIndicator.js:39:18
at tryCatcher (/var/www/node/messenger/node_modules/facebook-chat-api/node_modules/bluebird/js/main/util.js:26:23)
at Promise._settlePromiseFromHandler (/var/www/node/messenger/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:510:31)
at Promise._settlePromiseAt (/var/www/node/messenger/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:584:18)
at Promise._settlePromises (/var/www/node/messenger/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:700:14)
at Async._drainQueue (/var/www/node/messenger/node_modules/facebook-chat-api/node_modules/bluebird/ …
```

sendTypingIndicator: make callback optional

---

DOCS.md
src/getThreadInfo.js
utils.js

The data you get from threads in `getThreadInfo` and `getThreadList` are wildly different. This PR adds the data in `getThreadInfo` that wasn't into `utils.formatThread` and applies `utils.formatThread` to the thread in `getThreadInfo` so that you could get the same data you get from threads in `getThreadList` in `getThreadInfo`.

Fix inconsistencies between thread data in getThreadInfo and getThreadList

---

DOCS.md
index.js
src/getEmojiUrl.js
utils.js

#467 
Example usage:
`utils.getEmojiUrl('🐍', 128)` returns `https://static.xx.fbcdn.net/images/emoji.php/v8/ze1/1.5/128/1f40d.png` which is the emoji asset url for the snake emoji:

Utility function for getting the image URL for a Messenger-style emoji

---

DOCS.md

An attempt to fix #463 ([see here for what changes this makes](https://github.com/mrkno/facebook-chat-api/blob/fix/463-refactor-listen-docs/DOCS.md#listen))
It looks **a lot** nicer and more readable now. For the message/event object I ended up using plain HTML, as the markdown table was becoming very unreadable/maintainable and did not give the flexibility to do things such as rowspan.
Hopefully this is how you wanted it to look :)

Refactor listen docs

---

src/getThreadHistoryGraphQL.js

Adds `MessageAudio` attachment type to GraphQL version of `getThreadHistory` (`getThreadHistoryGraphQL`). I've tried to keep and copy the naming conventions of the fields from the other attachment types
Think this fixes #383 as well.
I've discard some fields for the user and kept what I think is appropriate but I'd be happy to add/remove any fields that you might think should be changed.

Add MessageAudio attachment type

---

src/sendMessage.js

Fix issue where sendMessage is unable to tag other users due to a Facebook change.
https://github.com/Schmavery/facebook-chat-api/issues/507

Fix sendMessage being unable to tag names

---

src/getThreadHistory.js

Fixes #520
Use 'Facebook User' as sender_name for no longer available accounts

Use a default name for unavailable accounts

---

src/listen.js

This is a workaround for the issue that caused the console to get
infinitely spammed with the same error over and over again.

listen: Better handle errors thrown from formatDeltaMessage

---

src/getThreadHistoryGraphQL.js

* Made several attachment field values conditionally null if specified element does not exist.
Previously, `formatExtensibleAttachment()` was failing on certain types of attachments -- i.e., attachments with missing `attachment.story_attachment.source` or `attachment.story_attachment.media` fields.

getThreadInfoGraphQL.js:formatExtensibleAttachment() fixes

---

DOCS.md
utils.js

Alright, I think this is now ready. I thought it through many times, and this is the easiest way to reduce the noisiness of the `proxy-presence` thing. If it contains an update (aka a _status code_), it fires, if not, then it won't. What does everyone think about this?
(Fixes #549)

Rewrite presence

---

src/getThreadHistoryGraphQL.js
utils.js

Extensible attachments were returning errors both in listen and getThreadHistoryGraphQL. This fixes the misspelling for the former and the error handling for the latter.

Extensible attachment fixes

---

utils.js

Follow up to #604 and fixes #632
Redirecting on the main page (#604) doesn't fix everything on the affected networks, as some GET requests (particularly the getUserID function) return an object with the proper URL they should redirect to.

Follow redirects on GET requests

---

package.json

(saves 7,46MB of download on `npm install`)

Moved prettier to dev-dependencies, fixed scripts

---

src/listen.js

**Facebook is now killing Messenger Platform for Pages!**
Now apps want to be reviewed must be associated to a business. Sadly, they will ask you to provide documents to prove that your business is real and is making money.
With this change we can use this api instead of the dead one provided by Facebook.
Please merge this change, so the poor like me can have some hope.. and not something like Chatfuel which has a very limited range of features.

Fix support for page listener

---

index.js
package-lock.json
src/listen.js
src/logout.js
utils.js

Facebook uses user agent as a factor when deciding if a login attempt is legitimate or not.
If you use facebook-chat-api on a hosted server (gcp, aws, azure, heroku, etc.) there is a high chance your login attempt gets blocked (this is from my experience) and account temporarily locked. However, by using your real user agent string FB tends to recognize chat-api as legitimate requests.
This PR allows someone to specify a custom user-agent if they wish otherwise defaults to the Mac OS X one already in this codebase.
EDIT: It might be more friendly to make this a login param instead?

Allow setting User Agent using an environment variable

---

CHANGELOG.md
DOCS.md
README.md
index.js
src/changeAdminStatus.js

few days ago I've made similar function to #658
But I didn't have time to write docs so I didn't pushed it to Github
It looks a bit cleaner IMO
I've also done some tests in the wild
and you can change `adminStatus` of every user in thread without being blocked by Facebook
but if you try to do the same thing one by one... Facebook blocks you for an hour :(

Add api.changeAdminStatus

---

package-lock.json
package.json

I updated the cheerio package from 0.19.0 to 0.22.0 This should get rid of the security warning on npm install. Mocha needs to be updated as well but I don't know if it will break testing.

update cheerio version 0.19.0 to 0.22.0

---

README.md

[messen](https://github.com/tomquirk/messen) is a new project of mine that aims to make it easy to build Facebook Messenger apps (using `facebook-chat-api`) in Node.js. Would love to have it on your list!

add `messen` to "projects using this api

---

index.js

Added `unsendMessage `to `apiFuncNames`, not doing this results in a `TypeError: api.unsendMessage is not a function`

Added unsendMessage to apiFuncNames in index.js

---

DOCS.md

The current docs for [login](https://github.com/Schmavery/facebook-chat-api/blob/master/DOCS.md#login) have a slight error in the code for login approvals/2 factor auth. In the code example, a variable `obj` is used, but it is not defined, resulting in a `ReferenceError`. This diff adds a definition for `obj` in the code example.

[docs] Define obj variable in docs for login with login approvals/2fa

---

src/sendMessage.js

Hello. If I use `api.sendMessage` without the last argument (reply message id), I get `MessageID should be of type string and not String.` So I fixed it in this PR.

Fix incorrect error assumption in sendMessage

---

DOCS.md
index.js
src/listenMqtt.js
src/markAsDelivered.js

Facebook in the browser marks new messages as delivered, So I added that here with the abillity to make it automatic (On by default). Also made an option to make markAsRead automatic but it's not on by default.
I don't know for sure if marking messages as delivered helps with the issue of accounts getting blocked, but it's better to do it anyway.
I fixed an issue I saw in #763 related to listenMqtt too.
Also added the docs to these new changes.
Thanks!

Support for markAsDelivered and auto message delivery and reading.

---

src/setMessageReaction.js

Facebook changed the backend to allow arbitrary emojis to be passed as reactions to messages. These changes can be seen already via `listen`, but can't be sent from the API because we do a check against what were previously the only valid emojis allowed in the call.
This PR just removes that validation so that any arbitrary reacts can be set on a message via the API.
(Tested it manually and it works)

Remove validation check for reacts

---

src/listenMqtt.js

Sometimes, with sticker message in group, delta does not contain 'attachments' property.

Handle when delta does not contain attachments property

---

README.md

The method list in the `DOCS.md` file contains a link to the `listenMqtt` method, but the method list in the main `README.md` file does not include this. As a result, it is unclear that this method is available to someone browsing through the documentation from the readme — for instance, as I was using the API, I only saw the readme initially and assumed the `listen` method was the only way to listen for messages.

Add listenMqtt to README.md

---

src/sendMessage.js

Calling many times getUserInfo very quickly can block this function and then sending messages becomes impossible, this way we're not calling this function when sending messages. Tested in groups and private messaging and it does work.

Change the way of checking if an ID is a user or a group when sending messages
