Schmavery/facebook-chat-api

index.js
This creates the option of using login() with a javascript object, instead of reading from file. Convenient, since you're probably parsing a file anyways, no need to do it twice.
=> Added option of logging in via json

README.md
You were passing a string to the login object, when in actuality, you had to pass an actual object. Fixed the error by using `fs` to read from the config file.
=> Fixed README error

config.json, index.js
This doesn't seem to affect anything..
I guess you forgot to remove it before pushing?
=> Remove unneeded stuff

utils.js
self explanatory. Pretty much takes care of any file attachments you throw at it. Tried adding photo attachments, but the url returned was super weird and didn't work (something along the lines of /ajax/mercury/attachements...). Will add if I find a way to do it.
=> Added way to get file attachment

index.js, src/getCurrentUserId.js
Much simpler and less cookie orientated method to get the current user! 
Usage example:
var UserID = api.getCurrentUserId();
*Note to self: explore more of the code before contributing!*
=> Adding getCurrentUserId endpoint

src/listen.js
=> Fix type comparison while listening for page messages

README.md, src/sendMessage.js
=> Added ability to start a new group chat!

index.js, src/listen.js, src/logout.js
Fixes issue #57 by not calling listen callback unless logged in :+1: :smile:
=> Fix logout

DOCS.md, README.md, index.js
If there are any ambiguities or typos, let me know!
=> Docs update!

DOCS.md
* Add api.getAppState()
* Add example usage of appState to/from files to login()
=> Update Docs to reflect appState capabilities

DOCS.md
Fixes a few errors in the API documentation
=> Correct errors in documentation

index.js
They look like they used to work but Facebook has changed the format of the form.
I spent some time on this (out of time for today) and I found one tweak we need. :beers: if you could take it from here.
=> It seems 2FA (login approvals) do not work any more

src/sendMessage.js
The error message for an invalid message type was logging the wrong variable.
=> Fix message type error log

src/getUserInfo.js
Hmm, interesting (if it works) how can working this function, but in Browser is request sent as POST, not GET.
=> Changed POST from GET in request

DOCS.md, src/listen.js, utils.js
This feature is able to know what time does the user himself read someone's messages.
=> Add read event

utils.js
=> prevent map breaking group messages

src/getThreadHistory.js
=> Fix issue where getThreadHistory returns extra message.

README.md
Fbash is a node module that is installed globally. The user can start it by running the command `fbash` and then enter their Facebook credentials to log in. After it has been started, the user can send messages to their own Facebook account to have them run as commands on the connected computer. Its on npm here: https://www.npmjs.com/package/fbash
=> Add fbash under 'Projects using this API'

DOCS.md, src/getThreadList.js
changed pending boolean to String so that "archived" messages can be reached.
=> "type" for getThreadList

DOCS.md, utils.js
Updated to follow a change in the way Facebook shows user presence on Messenger
=> Fix for #362

DOCS.md, index.js, src/createPoll.js
Fixed #382 to allow omission of `options` parameter in favor of a callback & to change the format to `optionTitle: selectedState`.
=> Add createPoll function

DOCS.md, README.md, index.js, src/getThreadPictures.js
Basic implementation for [#288](https://github.com/Schmavery/facebook-chat-api/issues/288)
=> Add getThreadPictures implementation

DOCS.md, src/listen.js, test/data/shareAttach.js, test/test.js, utils.js
fix #402 
Not directly related: I think we should break `listen` to several functions to be able to test it better.
=> fix: support full share attachments to fix facebook buttons

utils.js
=> Adding forgotten formatDeltaReadReceipt definition

utils.js
=> Adding retry limit

DOCS.md, README.md, src/setMessageReaction.js
change `addReaction` to `setReaction` in error message
place docs to setReaction in alphabetical order
make table with emojis
remove some trailing spaces
=> fixes to setReaction

src/listen.js
Fixing #442 @ravkr could you test it?
=> Implemented Reaction Emoji decoding

src/getThreadHistory.js, src/listen.js, utils.js
=> getThreadHistory: handle log entry ("event") data properly

DOCS.md, README.md, src/getUserID.js
=> Allow the first result for a search to be a non user and include the type in the returned data

README.md
Messer has been steadily growing in the last few months ( ⭐️ 110 as of this submission) and it is built on this wonderful project. Thought it best to add it to the list!
=> update README -> add Messer to Projects section

README.md
We renamed Kassy to Concierge a while back (much better name if you ask me) and significantly expanded its feature set.
=> Kassy has been renamed Concierge

DOCS.md, utils.js
Changed mentions from an array of ID's to an object containing the ID of the people tagged and the names that they were tagged with.
=> Update mentions to include names of people being mentioned/tagged

utils.js
=> Add support for MessageVideo and MessageAudio attachments

README.md
Another one for the list if you'd like :)
=> Add AssumeZero-Bot to projects list

src/getThreadInfoGraphQL.js
=> Update doc id for getThreadInfoGraphQL (#578)

src/getThreadHistoryGraphQL.js
getThreadHistory equivalent of #579
=> update getThreadHistoryGraphQL with the new doc_id

utils.js
fixes #607 and #587
can you test it @Bjornskjald ?
=> Fix crash on plan creation

index.js
Fixes #592 
Please let me know if there is a better way to do this.
=> Attempt to fix redirection to certain Facebook subdomains

src/getThreadHistoryGraphQL.js
I tried to export 200 000 messages from my messenger conversations. getThreadHistory does not work currently (#534) so I used the new version getThreadHistoryGraphQL(). I have some parsing errors which I have fixes (mainly null fields or not detected).
=> Add support for many type of events and MessageAnimatedImage attachments

utils.js
=> Fix response handling with multiple objects (#616)

src/getThreadHistory.js
=> Fix blob attachment variable in getThreadHistory

DOCS.md
Fixed a small oversight in the document
=> Fix a missing parenthesis

DOCS.md, index.js, src/getThreadList.js, src/getThreadListDeprecated.js
as old getThreadList stopped working (and now returns only empty array) just started making new version
there is separate field with id for group conversations and "one to one" conversations...
should I merge them to just one "threadID"?
=> Add getThreadList using GraphQL

.travis.yml, index.js, package.json, utils.js
Maybe this can help catch some simple bugs.
=> Add eslint error checking w/ travis

DOCS.md
=> Add note about updatePresence to docs of listen()

src/changeAdminStatus.js, src/changeGroupImage.js, src/changeNickname.js, src/changeThreadColor.js, src/changeThreadEmoji.js, src/createPoll.js, src/forwardAttachment.js, src/setMessageReaction.js, src/setTitle.js
Change from www.messenger.com -> www.facebook.com to prevent "Not logged in" error.
=> Changing all domain to www.facebook.com

DOCS.md, README.md, src/listen.js, src/unsendMessage.js
Facebook was updated with a new feature called "Unsend message". So here is my implentation for that feature.
Sorry if my English sucks. English is not my main language.
=> Unsend message feature.

README.md
Hello,
I find out that Facebook offers [Whitehat accounts](https://www.facebook.com/whitehat/accounts/), which are used for investigating security vulnerabilities. They're pretty great, it's absolutely same as normal Facebook account, just it's isolated, and you can't get blocked. I tested a facebook-chat-api with those accounts, it's works greatly, just it's little bit slower (but maybe that's because of my internet)
=> Way of testing the bots without creating another account

src/getThreadHistory.js, src/getThreadList.js, src/markAsRead.js
=> Fix api.markAsRead() for Facebook pages

DOCS.md
Updating to include this commit https://github.com/Schmavery/facebook-chat-api/commit/7470cfe9b29d30f082f76cacc08748e4e19e8c15
=> Added userAgent to setOption parameters

DOCS.md
Minor changes in DOCS.md for the unsendMessage method
=> Minor changes in DOCS.md

src/listen.js
This PR would allow the users of the [matrix facebook puppet bridge](https://github.com/matrix-hacks/matrix-puppet-facebook) to detect changes in polls.
=> Added support to detect changes in polls

src/listenMqtt.js, src/mqtt/fbconnect.js, src/mqtt/fbws.js
This fixes some errors with mqtt. I also made the mqtt connecting a little better.
I would like to ask If I should do #771 too.
Another thing is that I want to refactor some stuff to support new events better and I want to do something like #628 to make everything clear and better.
Thanks!
=> Bug fixes. closes #775

README.md
Replaces the project link in the Readme
=> Renamed project "TestMyBot" to "Botium" last year

src/listenMqtt.js
- Change ID type from `number` to `string` (Schmavery#771)
- Fix some perfomance issues (if callback takes a very longgggggggg time to resolve, it will lead to disconnection of MQTT) => wrap callback in a function so it will not block other calls to callback
=> Fixes for listenMqtt

src/listenMqtt.js
Finally added support for pages using mqtt.
=> Added support for pages.

index.js
Removed pull because it's not used anymore by Facebook. Fixes #794
=> Removed pull

package-lock.json, package.json, utils.js
A review of the code indicates that no other parts are affected by the breaking changes in the library update.
=> Updates bluebird to version 3.

index.js, src/listenMqtt.js
Fixed listenMqtt not working if stopped and ran again from the same instance. (#801).
Also fixed an error with thread images being sometimes undefined. (#787).
=> Fix some issues in MQTT.

src/getThreadHistory.js
This change fixed a crash on a thread I was enumerating. Let me know if you need further proof / documentation.
=> Added null check on sticker pack object
